- Instead of calling get_servant() directly on an instance of   org.omg.PortableServant.Current, do it via org.jacorb.poa.Current.   This change makes JacORB compatible with the obsolete version of   org.omg.PortableServant.Current in Sun's JDK 1.4.2, which does not have   the method get_servant().
- Removed catch clause for NoSuchMethodError, which will not occur anymore.